name: text_form_builder
description: A flutter package to build simple forms with custom widgets more easily.
version: 0.0.1
author: Leon Schneider <leon.flutter@cosolution.de>
homepage: https://github.com/leon175/text_form_builder

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
